thomas_platform_homepage:
    path:     /
    defaults: { _controller: ThomasPlatformBundle:Default:index }

hello_the_world:
    path:     /hello-world
    defaults: { _controller: ThomasPlatformBundle:Advert:index }