thomas_core:
    resource: "@ThomasCoreBundle/Resources/config/routing.yml"
    prefix:   /

thomas_platform:
    resource: "@ThomasPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform

login:
    path: /login
    defaults:
        _controller: ThomasUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout