<?php

namespace Thomas\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * MyOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MyOrderRepository extends \Doctrine\ORM\EntityRepository
{

    public function findOrders($page, $nbPerPage)
    {

        $qb = $this->createQueryBuilder('m')
            // ->leftJoin('u.user', 'o')
            // ->addSelect('o')
            ->orderBy('m.amount', 'DESC')
            ->getQuery()
            ;



        $qb
            ->setFirstResult(($page-1) * $nbPerPage)
            ->setMaxResults($nbPerPage)
        ;

        return new Paginator($qb, true);
    }
}
