<?php

namespace Thomas\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{

    public function findProducts($page, $nbPerPage, $category = null, $brand = null, $system = null, $name = null)
    {


        $qb = $this->createQueryBuilder('p');
        
        if ($category) {
            $qb
                ->andWhere('p.productCategory = :category')
                ->setParameter('category', $category)
            ;
        }
        if ($brand) {
            $qb
                ->andWhere('p.brand = :brand')
                ->setParameter('brand', $brand)
            ;
        }
        if ($system) {
            $qb
                ->andWhere('p.system = :system')
                ->setParameter('system', $system)
            ;
        }

        if ($name) {
            $qb
                ->andWhere('p.name like :name')
                ->setParameter('name', '%'.$name.'%')
            ;
        }

        $qb
            ->setFirstResult(($page-1) * $nbPerPage)
            ->setMaxResults($nbPerPage)
        ;
        $qb->getQuery();

        return new Paginator($qb, true);
    }

    public function findGames($page, $nbPerPage, $system = null, $name = null)
    {
        $qb = $this->createQueryBuilder('p');
        $qb
            ->where('p.productCategory = 1')
        ;
        if ($system) {
            $qb
                ->andWhere('p.system = :system')
                ->setParameter('system', $system)
            ;
        }

        if ($name) {
            $qb
                ->andWhere('p.name like :name')
                ->setParameter('name', '%'.$name.'%')
            ;
        }

        $qb
            ->setFirstResult(($page-1) * $nbPerPage)
            ->setMaxResults($nbPerPage)
        ;
        $qb->getQuery();


        return new Paginator($qb, true);

    }

    public function findSystems($brand = null)
    {
        $qb = $this->createQueryBuilder('p');
        $qb
            ->where('p.productCategory = 2')
        ;

        if ($brand) {
            $qb
                ->andWhere('p.brand = :brand')
                ->setParameter('brand', $brand)
            ;
        }

        return $qb
            ->getQuery()
            ->getResult()
        ;
    }

    public function findSuggestions($filter = null, $id = null, $limit = null)
    {
        $qb = $this->createQueryBuilder('p');
        $qb
            ->where('p.system = :filter')
            ->setParameter('filter', $filter)
            ->andWhere('p.id != :id')
            ->setParameter('id', $id)
            ->setMaxResults($limit)
        ;


        return $qb
            ->getQuery()
            ->getResult()
        ;
    }

    public function findAccess()
    {
        $qb = $this->createQueryBuilder('p');

        // On peut ajouter ce qu'on veut avant
        $qb
            ->where('p.productCategory = 3')
        ;
        return $qb
            ->getQuery()
            ->getResult()
        ;
    }

    public function search($string)
    {
        $qb = $this->createQueryBuilder('p');

        // On peut ajouter ce qu'on veut avant
        $qb
            ->where('p.productCategory = 3')
        ;
        return $qb
            ->getQuery()
            ->getResult()
        ;
    }
}
