<?php

namespace Thomas\CoreBundle\Repository;

/**
 * RateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RateRepository extends \Doctrine\ORM\EntityRepository
{

    public function findRate($id = null)
    {
        $qb = $this->createQueryBuilder('r');
        $qb
            ->where('r.product = :id')
            ->setParameter('id', $id)
        ;


        return $qb
            ->getQuery()
            ->getResult()
        ;
    }
}
