<?php

namespace Thomas\CoreBundle\Repository;

/**
 * StatuteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatuteRepository extends \Doctrine\ORM\EntityRepository
{
}
