<?php

namespace Thomas\CoreBundle\Repository;

/**
 * SystemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemRepository extends \Doctrine\ORM\EntityRepository
{
}
