thomas_back_office_homepage:
    path:     /
    defaults: { _controller: ThomasBackOfficeBundle:Default:index }

# PRODUITS

thomas_back_office_product_index:
    path:     products
    defaults: { _controller: ThomasBackOfficeBundle:Product:index }

thomas_back_office_product_view:
    path:     /product/{id}
    defaults: { _controller: ThomasBackOfficeBundle:Product:view }

thomas_back_office_product_edit:
    path:     /product-edit/{id}
    defaults: { _controller: ThomasBackOfficeBundle:Product:edit }

thomas_back_office_product_add:
    path:     /product-add
    defaults: { _controller: ThomasBackOfficeBundle:Product:add }

thomas_back_office_product_delete:
    path:     /product-delete/{id}
    defaults: { _controller: ThomasBackOfficeBundle:Product:delete }


# USERS

thomas_back_office_users:
    path:     users
    defaults: { _controller: ThomasBackOfficeBundle:User:index }

# ORDERS

thomas_back_office_orders:
    path:     orders
    defaults: { _controller: ThomasBackOfficeBundle:Order:index }

thomas_back_office_order_view:
    path:     order/{id}
    defaults: { _controller: ThomasBackOfficeBundle:Order:view }


# SETTINGS

thomas_back_office_settings:
    path:     settings
    defaults: { _controller: ThomasBackOfficeBundle:Setting:index }

thomas_back_office_setting_edit:
    path:     settings/{id}
    defaults: { _controller: ThomasBackOfficeBundle:Setting:edit }
