thomas_back_office_homepage:
    path:     /
    defaults: { _controller: ThomasBackOfficeBundle:Default:index }

# PRODUITS

thomas_back_office_product_index:
    path:     products/{page}
    defaults: { _controller: ThomasBackOfficeBundle:Product:index }

thomas_back_office_product_view:
    path:     /product/{id}
    defaults: { _controller: ThomasBackOfficeBundle:Product:view }

thomas_back_office_product_edit:
    path:     /product-edit/{id}
    defaults: { _controller: ThomasBackOfficeBundle:Product:edit }

thomas_back_office_product_add:
    path:     /product-add
    defaults: { _controller: ThomasBackOfficeBundle:Product:add }

thomas_back_office_product_delete:
    path:     /product-delete/{id}
    defaults: { _controller: ThomasBackOfficeBundle:Product:delete }


# REMISES

thomas_back_office_coupon_index:
    path:     remises
    defaults: { _controller: ThomasBackOfficeBundle:Coupon:index }

thomas_back_office_coupon_view:
    path:     /remise/{id}
    defaults: { _controller: ThomasBackOfficeBundle:Coupon:view }

thomas_back_office_coupon_edit:
    path:     /remise-edit/{id}
    defaults: { _controller: ThomasBackOfficeBundle:Coupon:edit }

thomas_back_office_coupon_add:
    path:     /remise-add
    defaults: { _controller: ThomasBackOfficeBundle:Coupon:add }

thomas_back_office_coupon_delete:
    path:     /remise-delete/{id}
    defaults: { _controller: ThomasBackOfficeBundle:Coupon:delete }


# USERS

thomas_back_office_users:
    path:     users
    defaults: { _controller: ThomasBackOfficeBundle:User:index }

thomas_back_office_user_view:
    path:     user{id}
    defaults: { _controller: ThomasBackOfficeBundle:User:view }

# ORDERS

thomas_back_office_orders:
    path:     orders
    defaults: { _controller: ThomasBackOfficeBundle:Order:index }

thomas_back_office_pdf:
    path:     pdf/{id}
    defaults: { _controller: ThomasBackOfficeBundle:Order:pdf }

thomas_back_office_order_view:
    path:     order/{id}
    defaults: { _controller: ThomasBackOfficeBundle:Order:view }


# SETTINGS

thomas_back_office_settings:
    path:     settings
    defaults: { _controller: ThomasBackOfficeBundle:Setting:index }

thomas_back_office_setting_edit:
    path:     settings/{id}
    defaults: { _controller: ThomasBackOfficeBundle:Setting:edit }
