thomas_game_home:
    path:     /
    defaults: { _controller: ThomasGameBundle:Product:index }

thomas_game_cart:
    path:     /panier
    defaults: { _controller: ThomasGameBundle:Cart:index }

thomas_game_add:
    path:     /ajouter/{id}
    defaults: { _controller: ThomasGameBundle:Cart:add }

thomas_game_delete:
    path:     /effacer/{id}
    defaults: { _controller: ThomasGameBundle:Cart:delete }

thomas_game_remove:
    path:     /vider
    defaults: { _controller: ThomasGameBundle:Cart:removeCart }

thomas_game_add_qty:
    path:     /plus/{id}
    defaults: { _controller: ThomasGameBundle:Cart:addQty }

thomas_game_remove_qty:
    path:     /moins/{id}
    defaults: { _controller: ThomasGameBundle:Cart:removeQty }

thomas_game_order:
    path:     /commande
    defaults: { _controller: ThomasGameBundle:Order:recap }

thomas_game_valid:
    path:     /validation
    defaults: { _controller: ThomasGameBundle:Order:valid }



thomas_game_rate:
    path:     /avis/{id}
    defaults: { _controller: ThomasGameBundle:Product:rate }

thomas_rate_add:
    path:     /avis/{id}/{rate}
    defaults: { _controller: ThomasGameBundle:Product:rateAdd }


thomas_game_products:
    path:     /produits
    defaults: { _controller: ThomasGameBundle:Product:index }

thomas_game_systems:
    path:     /consoles
    defaults: { _controller: ThomasGameBundle:Product:systemIndex }

thomas_game_games:
    path:     /jeux/{page}
    defaults: { _controller: ThomasGameBundle:Product:gameIndex }

thomas_game_access:
    path:     /accessoires
    defaults: { _controller: ThomasGameBundle:Product:accessIndex }

thomas_game_view:
    path:      /product/{id}
    defaults:
        _controller: ThomasGameBundle:Product:view
    requirements:
        id: \d+


thomas_user_pdf:
    path:     pdf/{id}
    defaults: { _controller: ThomasGameBundle:Page:pdf }

thomas_game_user_order:
    path:     /ma-commande/{id}
    defaults: { _controller: ThomasGameBundle:Page:myorder }

thomas_game_user_orders:
    path:     /mes-commandes
    defaults: { _controller: ThomasGameBundle:Page:myorders }

thomas_game_user:
    path:     /profile
    defaults: { _controller: ThomasGameBundle:Page:profile }

thomas_game_qsn:
    path:     /qui-sommes-nous
    defaults: { _controller: ThomasGameBundle:Page:qsn }

thomas_game_ml:
    path:     /mentions-legales
    defaults: { _controller: ThomasGameBundle:Page:ml }

thomas_game_cgv:
    path:     /cgv
    defaults: { _controller: ThomasGameBundle:Page:cgv }

thomas_game_user_disable:
    path:     /desactiver
    defaults: { _controller: ThomasGameBundle:Page:disable }